### ISSUE TITLE
Broken results with seasonality options

### ISSUE THREAD

**Issue by mg515** [dafiti/causalimpact#31] opened 2019-04-05 09:46 UTC
Hey! Thanks for the python implementation of causal impact model. However, I run into issues when trying to model with the seasonality as well. [Original R model works fine on this dataset.](https://rpubs.com/rinaldif/volkswagen-causal-impact)

The inference results are weird and the plotting is completely off. Let me know if you can't reproduce and I will include my results as well.

I also have problems applying your model on other datasets, same issues.

```
import numpy as np
import pandas as pd
from causalimpact import CausalImpact

np.random.seed(666)

series = pd.read_csv('vwseries.csv', header=0, sep=' ', index_col='Date')

dates = np.array(series.index)

pre_period = [np.min(dates), "2015-09-13"]
post_period = ["2015-09-20", np.max(dates)]

s_monthly = {'period': 30, 'harmonics': 7}
s_weekly = {'period': 7, 'harmonics': 1}

ci = CausalImpact(series, pre_period, post_period, prior_level_sd=0.05, niter=1000, nseasons=[s_monthly, s_weekly])

print(ci.summary())
ci.plot()
```

[Link to the csv file](https://drive.google.com/file/d/11zkZAl0Ev3wTqZJ7zAhEfq6x33M_CxRX)

**Comment by WillianFuks** [comment] 2019-04-05 12:02
Hi @mg515 , thanks a lot for reporting this!

I'll take a look to see what's going on here.

**Comment by WillianFuks** [comment] 2019-04-05 13:00
Hi @mg515 ,

Just to let you know, the problem is indeed in the predictions being made by `statsmodels` when using seasonality components. The very first points seems to not be able to converge to expected values; here's an example with your data:

```
In [74]: ci.inferences['preds_lower']                                                                                                                    
Out[74]: 
2011-01-09   -125763.646017
2011-01-16   -118570.540523
2011-01-23   -118567.566832
2011-01-30        84.117733
2011-02-06        94.272119
2011-02-13        90.112274
2011-02-20        84.104733
2011-02-27        84.757084
```

And then it finally converges. I'll research this problem to find out what's going on.

**Comment by mg515** [comment] 2019-04-05 13:45
Thanks a lot for the fast reply. Hope we can get to the bottom of this. :)

**Comment by joshtemple** [comment] 2019-04-12 17:09
I'm also experiencing this issue with my data with weekly seasonality. (period = 7) `ci.inferences['preds_lower']` looks similar to the way @WillianFuks showed it above.

**Comment by WillianFuks** [comment] 2019-04-13 04:09
Hello @mg515 ,

I've just pushed to origin in branch `check_season_bug` a fix for the problem you have reported.

Basically, what happened is that the Kalman filter technique which this library relies upon can use up to `n` data points considered as a "burning phase" period. So far, this burn period has been of length of just 1 so we never observed this issue before. Now, by using seasonal components in a real world data, the burning phase extended itself up to 53 points which should be removed from the predictions as otherwise the result is the weird plots you observed.

As I've just being using well behaved time series for the most part (here at Dafiti our data has a very strong weakly component which already is fully described by a season {'period': 7} for instance) I never observed this issue and didn't test for it.

Now the code is fully tested and covered on this topic.

We wrote a new section in our examples notebook, if you could please read it to tell us what you think that would be very cool :)! If you confirm everything is working for you I'll push these changes to master and publish a new release to PyPI.

Here's the link for the [notebook](https://nbviewer.jupyter.org/github/dafiti/causalimpact/blob/check_season_bug/examples/getting_started.ipynb#2.6-More-Real-Data-Example).

Notice, despite having similar results to the R package, we carry some discussion about the level prior parameter. As we state in our notebook, in this Python implementation, best option usually is to let the parameter be free to be optimized (which means sending it explicitly as  `prior_level_sd=None`; it may change in future releases).

The idea is to rely on the prior level only if you are confident about how the data behaves which, in the example of the stocks prices you presented, it probably is not that well behaved as one would wish :).

Once again, thanks for reporting us this issue, now the library is much more robust with the new changes made.

Best Regards,

Will

**Comment by joshtemple** [comment] 2019-04-24 18:17
Thanks for pushing out this fix! @WillianFuks, I've tested my code with the new branch and the output is now consistent with what I expect it to be.

However, I do get this warning every time:

```
statsmodels/base/model.py:508: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)
```

**Comment by WillianFuks** [comment] 2019-04-24 18:41
Hi @joshtemple ,

Thanks for testing the branch :)! I'll probably push it to master soon enough.

Now this convergence warning seems to be happening in the optimization from scipy that statsmodels uses, might be something related to the data itself (maybe not enough data points to converge or something alike). Can you share your data or a sample of it? I'll also try to simulate it on my side to see if I find what's going on.

Thanks once again,

Will

**Comment by joshtemple** [comment] 2019-04-24 18:45
Unfortunately I won't be able to share the actual data, but I'm happy to look deeper for the source of this warning if you give me some guidance of where and how to look!

**Comment by WillianFuks** [comment] 2019-04-24 19:14
No worries. Not sure how to debug this one but as the message states, maybe the returned values from the optimization has some information we could use.

Could you please send us what you get for `ci.trained_model.mle_retvals` ?

Probably you'll see 50 iterations which is default and not enough to converge.

**Comment by joshtemple** [comment] 2019-04-24 21:40
Here's what I get from `ci.trained_model.mle_retvals`:

```
{'fopt': 0.3369751621337168,
 'gopt': array([ 3.58832741e-05,  5.95414895e-04,  1.96225403e-03, -5.34077227e-05,
        -1.47570189e-04, -2.51959043e-04,  4.17265306e-04,  4.13518064e-04,
         3.92416905e-04, -1.89181304e-04]),
 'fcalls': 715,
 'warnflag': 1,
 'converged': False,
 'iterations': 50}
```

**Comment by WillianFuks** [comment] 2019-04-26 21:48
Hi @joshtemple ,

Thanks for the reply. I wonder what happens if you allow for more iterations in the optimization process.

This can be done by adding `maxiter` to the model constructor, something like:

    ci = CausalImpact(data, pre_period, post_period, maxiter=200)

You can play around with the value, probably ranging from 100 up to 500 maybe to see what happens.

I'll close this issue by now as I'll upload the new code to PyPI, please feel free to comment on this thread or open new issues if you observe unexpected results.

Thanks for the help on this issue :)!

**Closed by WillianFuks** 2019-04-26 21:48 UTC
Labels: bug
