### ISSUE TITLE
Problems with autoregressive models

### ISSUE THREAD

**Issue by rcalsaverini** [dafiti/causalimpact#49] opened 2019-10-28 22:52 UTC
I'm trying to test the passing a custom model as described by the documentation, but when I turn on the `autoregressive` parameter in the model, there's an exception when fitting the Causal Impact model:

Here's a minimal example that reproduces the problem:

```python
import numpy as np
import pandas as pd
from statsmodels.tsa.statespace.structural import UnobservedComponents
from causalimpact import CausalImpact
from causalimpact.misc import standardize


N = 100
switch_point = 70
np.random.seed(12345)
X = np.random.normal(0, 1, size=N)
y = X + np.random.normal(size=N)
y[switch_point:] += 5

data = pd.DataFrame({'y': y, 'X': X})
pre_period = [0, switch_point - 1]
post_period = [switch_point, N - 1]

normed_pre_data, _ = standardize(data.iloc[:switch_point])

model = UnobservedComponents(
    endog=normed_pre_data.iloc[:switch_point, 0],
    exog=normed_pre_data.iloc[:switch_point, 1:],
    autoregressive=True,
    level="llevel"
)

ci_model = CausalImpact(data, pre_period, post_period, model=model)
ci_model.plot(panels=['pointwise'], figsize=(15, 4))
```
When I run this I get the following traceback:

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-537cc248980b> in <module>
     26 )
     27 
---> 28 ci_model = CausalImpact(data, pre_period, post_period, model=model)
     29 ci_model.plot(panels=['pointwise'], figsize=(15, 4))

~/dev/sandbox/python/causal_impact/.env/lib/python3.7/site-packages/causalimpact/main.py in __init__(self, data, pre_period, post_period, model, alpha, **kwargs)
    233         self.model = checked_input['model']
    234         self._fit_model()
--> 235         self._process_posterior_inferences()
    236 
    237     @property

~/dev/sandbox/python/causal_impact/.env/lib/python3.7/site-packages/causalimpact/main.py in _process_posterior_inferences(self)
    309         processed here.
    310         """
--> 311         self._compile_posterior_inferences()
    312         self._summarize_posterior_inferences()
    313 

~/dev/sandbox/python/causal_impact/.env/lib/python3.7/site-packages/causalimpact/inferences.py in _compile_posterior_inferences(self)
    248         post_cum_pred.index = self._get_cum_index()
    249         post_cum_pred_lower, post_cum_pred_upper = np.percentile(
--> 250             np.cumsum(self.simulated_y, axis=1),
    251             [lower, upper],
    252             axis=0

~/dev/sandbox/python/causal_impact/.env/lib/python3.7/site-packages/causalimpact/inferences.py in simulated_y(self)
    127                                                               predicted_state_cov)
    128                 sim = model.simulate(params, len(self.post_data),
--> 129                                      initial_state=initial_state)
    130                 if self.mu_sig:
    131                     sim = sim * self.mu_sig[1] + self.mu_sig[0]

~/dev/sandbox/python/causal_impact/.env/lib/python3.7/site-packages/statsmodels/tsa/statespace/mlemodel.py in simulate(self, params, nsimulations, measurement_shocks, state_shocks, initial_state)
   1445 
   1446         simulated_obs, simulated_states = self.ssm.simulate(
-> 1447             nsimulations, measurement_shocks, state_shocks, initial_state)
   1448 
   1449         # Simulated obs is (nobs x k_endog); don't want to squeeze in

~/dev/sandbox/python/causal_impact/.env/lib/python3.7/site-packages/statsmodels/tsa/statespace/kalman_filter.py in simulate(self, nsimulations, measurement_shocks, state_shocks, initial_state)
   1087 
   1088         return self._simulate(nsimulations, measurement_shocks, state_shocks,
-> 1089                               initial_state)
   1090 
   1091     def _simulate(self, nsimulations, measurement_shocks, state_shocks,

~/dev/sandbox/python/causal_impact/.env/lib/python3.7/site-packages/statsmodels/tsa/statespace/simulation_smoother.py in _simulate(self, nsimulations, measurement_shocks, state_shocks, initial_state)
    177             initial_state, dtype=self.dtype
    178         ).squeeze())
--> 179         simulator.set_initial_state(initial_state)
    180 
    181         # Perform simulation smoothing

statsmodels/tsa/statespace/_simulation_smoother.pyx in statsmodels.tsa.statespace._simulation_smoother.dSimulationSmoother.set_initial_state()

statsmodels/tsa/statespace/_simulation_smoother.pyx in statsmodels.tsa.statespace._simulation_smoother.dSimulationSmoother.set_initial_state()

statsmodels/tsa/statespace/_tools.pyx in statsmodels.tsa.statespace._tools.validate_vector_shape()

ValueError: Invalid shape for initial state vector: requires 1 rows, got 2
```

I'm using version 0.0.14, installed via pip:
```
pycausalimpact==0.0.14
statsmodels==0.10.1
```

**Comment by WillianFuks** [comment] 2019-10-29 01:11
Hey @rcalsaverini ,

Thanks for opening this issue :)

As it turns out, the variable name for `autoregression` changed in latest statsmodels versions; now it's named [autoregressive](https://github.com/statsmodels/statsmodels/blob/v0.10.0/statsmodels/tsa/statespace/structural.py#L75) whereas before it was just [ar](https://github.com/statsmodels/statsmodels/blob/v0.8.0/statsmodels/tsa/statespace/structural.py#L65).

As it turns out, our package [looks for this variable](https://github.com/dafiti/causalimpact/blob/master/causalimpact/misc.py#L115) to prepare a new model for making time series simulations and therefore is not working properly anymore.

I'll work on a fix for this issue, thanks once again for reporting this!

**Comment by rcalsaverini** [comment] 2019-10-29 17:12
I downgraded to statsmodels version 0.9.0 and it works alright. Maybe pinning the version of statsmodels to 0.9.0 is a good temporary fix while working on a permanent fix.

**Closed** 2019-10-30 13:05 UTC

**Comment by WillianFuks** [comment] 2019-10-30 13:26
Hi @rcalsaverini ,

I just merged a fix for this issue and publish the changes o PyPI, you can check the new code by running `pip install -U pycausalimpact`

Thanks for reporting this one :)!

If you find any issues just let me know.
